name       : waybar
version    : 0.9.16
release    : 5
source     :
    - https://github.com/Alexays/Waybar/archive/refs/tags/0.9.16.tar.gz : 37ebd7b10e32e802afe9236ea9374fabb77b1abb2c203ca6173b27dc03128096
license    : MIT
component  : system.utils
summary    : Highly customizable Wayland bar for Sway and Wlroots based compositors
description: |
    Highly customizable Wayland bar for Sway and Wlroots based compositors
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(fmt)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(jack)
    - pkgconfig(jsoncpp)
    - pkgconfig(libmpdclient)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(sndio)
    - pkgconfig(spdlog)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wireplumber-0.4)
    - chrono-date-devel
rundeps    :
    - font-awesome-ttf
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-config.patch
    %meson_configure -Dgtk-layer-shell=disabled -Dtests=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
