name       : waybar
version    : 0.9.8
release    : 2
source     :
    - https://github.com/Alexays/Waybar/archive/refs/tags/0.9.8.tar.gz : 3f067c484aaee3e7d8ded382e72c280a92913b0c4e8a20d0ac9afdf8baf19405
license    : MIT
component  : system.utils
summary    : Highly customizable Wayland bar for Sway and Wlroots based compositors
description: |
    Highly customizable Wayland bar for Sway and Wlroots based compositors
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(fmt)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libevdev)
    - pkgconfig(libmpdclient)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(spdlog)
    - chrono-date
    - sndio-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-support-stateless-config-for-waybar.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
